import type { Metadata } from 'next';
import { Geist, Geist_Mono } from "next/font/google";
import ReduxProvider from './store/ReduxProvider';
import ClerkWrapper from './ClerkWrapper';
import "./globals.css";

import 'bootstrap/dist/css/bootstrap.min.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GiftShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkWrapper>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </ClerkWrapper>
      </body>
    </html>
  );
}
