import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import ReduxProvider from '../store/ReduxProvider';

import 'bootstrap/dist/css/bootstrap.min.css';
import TopNav from '../_components/TopNav';
import Footer from '../_components/Footer';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    
    <ClerkProvider>
      <TopNav />
      <ReduxProvider>
        {children}
      </ReduxProvider>
      <Footer />
    </ClerkProvider>
  );
}
